CREATE TABLE "GCG_6816_LABOR_EXP" (
 "TRANS_NUM" CHAR(4),
 "EMPLOYEE" CHAR(5) NOT NULL,
 "TRANS_TYPE" CHAR(1),
 "JOB" CHAR(9) NOT NULL,
 "IND_CODE" CHAR(8),
 "START_TIME" CHAR(23),
 "END_TIME" CHAR(23),
 "HRS" NUMERIC(11,4),
 "QTY" NUMERIC(12,4) NOT NULL, 
 "SCRAP_QTY" NUMERIC(12,4),
 "JOB_OP" CHAR(6),
 "ERR_CODE" BIT); 